version: "3.8"
services:
  db:
    image: postgres:latest
    environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=TBM
    logging:
          options:
            max-size: 10m
            max-file: "3"
    ports:
      - 5438:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  web:
    build: ./web
    ports:
      - "80:80"
    environment:
      - VITE_URL=api:3000
  api:
    build: ./server
    ports:
      - 3000:3000
    environment:
      - HOST=db
      - DB=TBM
      - PASSDB=postgres
    depends_on:
      - db

